version: "3.9"
services:
  fastapi_tm_db:
    image: mysql:8
    container_name: fastapi_tm_db
    volumes:
      - ./data/mysql/data:/var/lib/postgresql/data
      - ./mysql_conf:/etc/mysql/conf.d
      - ./data/mysql/data:/var/lib/mysql
    networks:
      fastapi_tm_net:
        ipv4_address: 172.21.0.2
    restart: always
    environment:
      - TZ=Asia/Shanghai
      - LC_ALL=C.UTF-8
      - LANG=C.UTF-8
      - MYSQL_DATABASE=ftm_dev
      - MYSQL_ROOT_PASSWORD=12345678

  fastapi_tm_redis:
    image: redis:6.2.4
    container_name: fastapi_tm_redis
    networks:
      fastapi_tm_net:
        ipv4_address: 172.21.0.3
    restart: always
    volumes:
         - ./data/redis/data:/data
    command: redis-server --requirepass 12345678
    environment:
      - TZ=Asia/Shanghai
    depends_on:
      - fastapi_tm_db

  fastapi_tm_api:
    container_name: fastapi_tm_api
    image: "fastapi_tm_api:latest"
    build:
      context: "./api"
      dockerfile: ./Dockerfile
    volumes:
      - ./api:/home/project
      - ./conf/api/.env:/home/project/.env
      - ./conf/api/run.sh:/home/project/run.sh
      - ./data/api/logs:/home/logs
    ports:
      - 127.0.0.1:18020:8000
    networks:
      fastapi_tm_net:
        ipv4_address: 172.21.0.4
    restart: always
    depends_on:
      - fastapi_tm_redis
      - fastapi_tm_db

networks:
  fastapi_tm_net:
    external: true