[redis]

HOST = "172.22.0.3"
PORT = 6379
PASSWD = "12345678"

[db]

POOL_RECYCLE = 1800

USER = "root"
PASSWD = "12345678"
HOST = "172.22.0.2"
PORT = 3306
DATABASE = "ftm_dev"
MAX_SIZE = 500

[log]

LEVEL = "INFO"
PATH = "/home/user/srv/ftm/logs/local/x.log"

[service]
# schema swagger
INCLUDE_IN_SCHEMA = true

[authentic]

ADMIN_SECRETS = "SZjj5S8NgOcuq8LH+bAtDw=="
TOKEN_EXP_DELTA_ADMIN = 864000
