
[log]

LEVEL = "INFO"
PATH = "/home/logs/x-test.log"
STDOUT = true
ROTATION = "00:00"
RETENTION = "30 days"

[service]
# schema swagger
INCLUDE_IN_SCHEMA = true

[authentic]

ADMIN_SECRETS = "SZjj5S8NgOcuq8LH+bAtDw=="
TOKEN_EXP_DELTA_ADMIN = 864000

[redis]

HOST = "172.20.5.6"
PORT = 6379
PASSWD = "12345678"

[db]

POOL_RECYCLE = 1800

USER = "root"
PASSWD = "12345678"
HOST = "172.20.5.3"
PORT = 3306
DATABASE = "ftm_test"
MAX_SIZE = 500
