-- upgrade --
CREATE TABLE IF NOT EXISTS `orders` (
    `id` BIGINT NOT NULL PRIMARY KEY AUTO_INCREMENT COMMENT '主键',
    `created_at` DATETIME(6) NOT NULL  COMMENT '创建时间' DEFAULT CURRENT_TIMESTAMP(6),
    `updated_at` DATETIME(6) NOT NULL  COMMENT '更新时间' DEFAULT CURRENT_TIMESTAMP(6) ON UPDATE CURRENT_TIMESTAMP(6),
    `is_delete` BOOL NOT NULL  COMMENT '删除标识' DEFAULT 0,
    `amount` BIGINT NOT NULL  COMMENT '订单总额',
    `remarks` VARCHAR(300) NOT NULL  COMMENT '订单备注',
    `owner_id` BIGINT NOT NULL
) CHARACTER SET utf8mb4 COMMENT='订单表';
-- downgrade --
DROP TABLE IF EXISTS `orders`;
